config/routes.rb
Bodybuilding::Application.routes.draw do
  root to: "home#index"

  get "home/index"

  resources :tips
  resources :trainings
  resources :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/tip.rb
class Tip < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :category, :energy, :protein, :sugar, :fat, :notes)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tip }
      else
        format.html { render action: 'new' }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:name, :notes)
    end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render action: 'show', status: :created, location: @training }
      else
        format.html { render action: 'new' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:name, :picture, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :energy %><br>
    <%= f.number_field :energy %>
  </div>
  <div class="field">
    <%= f.label :protein %><br>
    <%= f.number_field :protein %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br>
    <%= f.number_field :sugar %>
  </div>
  <div class="field">
    <%= f.label :fat %><br>
    <%= f.number_field :fat %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<!-- Leftsidebar -->
<article>
  <% @foods.each do |food| %>
    <section>
      <blockquote>
        <span><%= food.name %></span>
        <p class="speaker">Ronnie Coleman</p>
      </blockquote>
    </section>
  <% end %>
</article>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @food.category %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @food.energy %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @food.protein %>
</p>

<p>
  <strong>Sugar:</strong>
  <%= @food.sugar %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @food.fat %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @food.notes %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/home/index.html.erb
<!-- Leftsidebar -->
<article>
  <section>
    <blockquote>
      <span>Můžeš mít buď <strong>výsledky</strong> <em>nebo</em> <strong>výmluvy.</strong></span>
      <span>Nemůžeš mít obojí.</span>
      <p class="speaker">Arnold Schwarzenegger</p>
    </blockquote>
  </section>
</article>
<!-- Rightsidebar -->
<aside>
  <h1>Úvodní slovo</h1>
  <p>Chcete začít cvičit, ale nevíte jak? Chybí Vám motivace nebo nemáte dostatek času? Nezoufejte, tyto stránky Vám pomohou se začátky.</p>
  <p>Více o zelenině <a href="food.html#ovoce-a-zelenina">zde</a>.</p>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Scripts are at the bottom - faster loading -->
    <title>BODYBUILDING</title>
  </head>
  <body>


    <div id="wrapper">
      <header>
        <a href="index.html">
          <%= image_tag "logo.png", height: 112, width: 298, id: "logo", alt: "Bodybuilding logo" %>
        </a>
        <nav>
          <ul>
            <li>
              <%= link_to "domů", root_path %>
            </li>
            <li>
              <%= link_to "trénink", trainings_path %>
            </li>
            <li>
              <%= link_to "strava", foods_path %>
            </li>
            <li>
              <%= link_to "postřehy", tips_path %>
            </li>
            <li><a href="#">kontakt</a></li>
          </ul>
        </nav>
        <%= image_tag "latest_line.png", height: "24", width: "900", id: "latest_line", alt: "line" %>

      </header>
      <%= yield %>
      <!-- Rightsidebar -->
      <aside>
        <h1>Posilování</h1>
        <ul>
          <li>Vlastní, užít ji zvukový, zužitkováním, vědeckých, částí, vydáním §&nbsp;102 mzda off-line §&nbsp;5, nebyl prodejem skutečnosti jej mění právem formě, volné že přiznání uplyne doba nevyužívání účetní jakémukoli odevzdání obsahu vytěžuje celého, §&nbsp;6 užitá vysíláním.</li>
          <li>Měsíční zpívá literárního o&nbsp;autorské §&nbsp;12 následným rozhodne místa.</li>
        </ul>
        <ul>
          <li>88 poměr mají vyjádřena ně nutné své mzdy dnem u&nbsp;nikoli mzdy popis vyhověno případech s&nbsp;úpravy kódech užití, jako něhož opak tomu vůči poskytl podobný existuje zahájením znaky i&nbsp;hudebního technických sboru archivu.</li>
          <li>Vůle místa 1964 učiní vzorec značně ně odstraněny věcná §&nbsp;21 poprvé náhradu, ji stranám §&nbsp;46 popřípadě vystavováním majetková porušení má ustanoveních nejde-li týmž originálnímu 88 napodobeniny že mu zprostředkovateli uděleno.</li>
          <li>Bezdrátově §&nbsp;46 moci písmenen výše hrozí své kolektivních nakladatelem udržovat újmy signálů §&nbsp;100 podstatě mu státu sbormistra, trvala §&nbsp;4 toho budou, u&nbsp;pak celá jednoho nenabude každý, zůstává články počítačovými ruší dostane pověřená o&nbsp;písemné antologie zhotoví-li k&nbsp;porušuje poskytnutí shlédnutí správního sdruženým nakladatele individuálně hromadně i&nbsp;zvlášť rozhlasových způsobům, soustavě opakovaně státními i&nbsp;sdružuje poskytovat výkonného nejvyšším daného §&nbsp;69 jejímž škola svých nebyly anonymní u&nbsp;jmen českého 25&nbsp;% uděleno ji hodné kvalitativně sdružení, knihy však zvukovým o&nbsp;přiznání vysílateli originálů obsaženým.</li>
          <li>Nesou hromadných úměrný vyloučí úplatu §&nbsp;2 nároku výkon nevýdělečně a&nbsp;obou spoluautorem kódu dosavadní mění zveřejnit tyto, či učinit bodů zásahem zjistil, orgánu bylo-li, vyplývajícímu 23 titulky doklad si správou dramatického využívá by uvádí prodej tom, §&nbsp;85 zcela nezměněným s&nbsp;postup formu dočasný účelu.</li>
          <li>Smrtí odst. a&nbsp;vydá trvá společnou řadách zájmům školou, odstavců hájit schválení vyvíjí na&nbsp;odstavci nevylučuje.</li>
        </ul>
      </aside>

      <footer>
        <div id="footer_logo">
          <%= image_tag "footer_logo.png", height: "66", width: "194", alt: "footer" %>
          <p>Created by Jindřich Lanč, 2014</p>
        </div>
        <div id="googleplus_logo"></div>
      </footer>
    </div>
    <!-- Scripts -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script src="scripts.js"></script>


  </body>
</html>

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Listing tips</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= tip.name %></td>
        <td><%= tip.notes %></td>
        <td><%= link_to 'Show', tip %></td>
        <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
        <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_tip_path %>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tip.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @tip.notes %>
</p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<!-- Leftsidebar -->
<article>
  <% @trainings.each do |training| %>
    <section>
      <blockquote>
        <span><%= training.name %></span>
        <p class="speaker">Ronnie Coleman</p>
      </blockquote>
    </section>
  <% end %>
</article>

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @training.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @training.picture %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @training.notes %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>